=== cwj57740/weibo-mvc/src/main/resources/apis.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="apis" type="apisType"/>
    <xsd:complexType name="apisType">
        <xsd:sequence>
            <xsd:element name="api" type="apiType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="apiType">
        <xsd:sequence>
            <xsd:element name="class" type="xsd:string"/>
            <xsd:element name="method" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="path" type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== cwj57740/weibo-mvc/src/main/resources/api-config.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<apis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="apis.xsd">
    <api path = "test">
        <class>cn.edu.hit.weibo.controller.TestController</class>
        <method>execute</method>
    </api>
    <api path = "Register">
        <class>cn.edu.hit.weibo.controller.RegisterController</class>
        <method>register</method>
    </api>
    <api path = "Login">
        <class>LoginController</class>
        <method>login</method>
    </api>
    <api path = "AddFriend">
        <class>cn.edu.hit.weibo.controller.FriendController</class>
        <method>addFriend</method>
    </api>
    <api path = "GetFriendList">
        <class>cn.edu.hit.weibo.controller.FriendController</class>
        <method>showFriendList</method>
    </api>

    <api path = "AddWeibo">
        <class>cn.edu.hit.weibo.controller.WeiboController</class>
        <method>addWeibo</method>
    </api>
    <api path = "GetWeiboList">
        <class>cn.edu.hit.weibo.controller.WeiboController</class>
        <method>getWeiboList</method>
    </api>
    <api path = "GetOwnWeiboList">
        <class>cn.edu.hit.weibo.controller.WeiboController</class>
        <method>getOwnWeiboList</method>
    </api>
    <api path = "AddComment">
        <class>cn.edu.hit.weibo.controller.WeiboController</class>
        <method>addComment</method>
    </api>
    <api path = "GetCommentList">
        <class>cn.edu.hit.weibo.controller.WeiboController</class>
        <method>getCommentList</method>
    </api>
</apis>
